export const properties = {
  header: 'MOORMANAGE/Boatyards',
  boatyardMooringHeader: 'Boatyard Moorings',
  serviceAreaMooringHeader: 'Service Area Moorings',
  boatyardDetail: 'Boatyards Detail',
  serviceAreaDetail: 'Service Area Detail',
  address: 'Address',
  mooringInventoried: 'Mooring Inventoried',
  boatyardGPSCoordinates: 'Boatyard GPS Coordinates',
  moormanagePermission: 'MOORMANAGE/Permission',
  CustomersOwner: 'Companies',
  CustomerOwnerUsers: 'User Management',
  label: 'ADD NEW',
  customerMooringHeader: 'Customer Moorings',
  MoormanageMoorings: 'MOORMANAGE/Moorings',
  Customersadmins: 'Customersadmins',
  workOrderHeader: 'Work Orders',
  customerHeader: 'Customers',
  customerRecord: 'Customers Record',
  mooringHeader: 'Moorings',
  Users: 'User Management',
  Settings: 'Customer Mapping',
  Technician: 'Technician',
  imageHeader: 'Images',
}
